config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated do
    root to: "restaurants#index", as: :authenticated
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    member do
      get 'like', to: "restaurants#like"
    end
  end
  get 'dashboard',  to: 'restaurants#dashboard'
  get 'profile', to: 'pages#profile'
  get 'qrcode', to: 'pages#qrcode'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :restaurant
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :users, through: :cards
  mount_uploader :photo, PhotoUploader

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  acts_as_favoritable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :restaurants, through: :cards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update,
      keys: [
        :first_name,
        :last_name,
        :phone_number,
        :photo])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    if params[:query].present?
      @restaurants = Restaurant.global_search("%#{params[:query]}%")
    else
      @restaurants = Restaurant.all
    end
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    if current_user.favorited?(@restaurant)
      current_user.unfavorite(@restaurant)
      result = {liked: false}
    else
      current_user.favorite(@restaurant)
      result = {liked: true}
    end
    render json: result
  end

  def dashboard
    @favorites = current_user.all_favorited
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :photo, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page">
      <%= yield %>
    </div>
    <%= render 'shared/navbar' if user_session %>
    <%= render 'shared/flashes' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>dashboard</h1>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <% @favorites.each do |favorite|%>
      <div class="card-category"  style="background-image: url('<%= cl_image_path favorite.photo, height: 300, width: 400, crop: :fill %>')">
        <div class="specialty-name"><%= link_to favorite.name, specialty_path(favorite), class: 'card-link' %>
        </div>
        <i class="far fa-heart favorites <%= current_user.favorited?(favorite) ? "liked" : "" %>" data-id="<%= favorite.id %>"></i>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1517433367423-c7e5b0f35086?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80);">
  <div class="container">
    <div class="d-flex flex-column d-flex justify-content-between" style="text-align: center; height: 50vh;">
    <i class="far fa-credit-card" style="color: white; font-size: 40px; opacity: 0.6;"></i>
    <%= link_to  user_session_path do %>
    <span class="btn btn-class btn-outline-light home-btn rounded-pill" style="width: 150px;">Log in</span>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 mx-auto py-4">
      <div class = "exlogform">
        <div class="d-flex flex-column justify-content-around">
          <div class="edit-link">
            <div class="c-title-user d-flex" style="padding-bottom: 0px;">
              <div>
                <% if user_signed_in? && current_user.photo.file %>
                <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                <%= image_tag 'non_existing_id.png' , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
              </div>
              <div class="div-design-title" style="margin-left: 15px;">
                <h3><%= current_user.first_name %>
                  <%= current_user.last_name %>
                </h3>
              </div>
            </div>
            <div>
              <%= link_to "Edit profil", edit_user_registration_path %>
            </div>
          </div>
          <div class="d-flex" style="padding-top: 20px;">
            <i class="fas fa-id-card"> </i>
            <p style="padding-left: 15px;">Payment</p>
          </div>
          <div>
            <p>Promotions</p>
          </div>
          <div>
            <p>Other stuff</p>
          </div>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/qrcode.html.erb
<div class="container justify-content-center">
  <div class = "d-flex justify-content-center" style="align-items: center; height: 100vh;">
    <canvas id="canvas"></canvas>
    <script src="bundle.js"></script>
    <div id="qrResult" style="height: 500px, width: 500px;"></div>
  </div>
</div>

app/views/restaurants/dashboard.html.erb
<div class="container">
  <div class="row">
    <% @favorites.each do |favorite| %>
    <div class="col-md-4 col-lg-3 my-3">
      <div class="card-trip-dash">
        <%= cl_image_tag favorite.photo %>
        <div class="card-trip-infos">
          <div>
            <div class="d-flex justify-content-between">
              <h2><%= favorite.name %></h2>
              <i class="far fa-heart favorites <%= current_user.favorited?(favorite) ? "liked" : "" %>" data-id="<%= favorite.id %>"></i>
            </div>

            <p><%= favorite.description %></p>
            <p> <%= favorite.address %> </p>
          </div>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="search-bar">
  <%= form_tag restaurants_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a restaurant"
    %>
    <%= submit_tag "Search", class: "btn btn-primary dis" %>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
    <div class="col-md-4 col-lg-3 my-3">
      <div class="card-trip">
        <%= cl_image_tag restaurant.photo %>
        <div class="card-trip-infos">
          <div>
            <div class="d-flex justify-content-between">
              <h2><%= restaurant.name %></h2>
              <i class="far fa-heart favorites <%= current_user.favorited?(restaurant) ? "liked" : "" %>" data-id="<%= restaurant.id %>"></i>
            </div>
            <p><%= restaurant.description %></p>
            <p> <%= restaurant.address %> </p>
          </div>
          <div class="points"><p> Points: 0/10 </p></div>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="position: sticky; bottom: 0;">
  <div class="container">
    <ul class="d-flex d-flex justify-content-around" style="list-style: none; width: 100%; padding: 0;">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to restaurants_path, class: "nav-link" do %>
            <i class="fas fa-home"></i>
          <%end%>
        </li>
        <li class="nav-item active">
          <%= link_to qrcode_path, class: "nav-link" do %>
            <i class="fas fa-qrcode"></i>
          <%end%>
        </li>
        <li class="nav-item active">
        <%= link_to dashboard_path, class: "nav-link mes-parties"  do %>
          <i class="fas fa-credit-card"></i>
        <% end %>
      </li>

      <li class="nav-item active">
        <%= link_to profile_path, class: "nav-link ta-partie" do %>
          <i class="fas fa-user"></i>
        <% end %>
      </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_test.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if user_signed_in? && current_user.photo.file %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag 'non_existing_id.png' , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>